### ISSUE TITLE
possible fan speed issue on macbookpro11,5

### ISSUE THREAD

**Issue by rahulmb** [ablakely/macfand#5]
Based on the RPMs being recorded as a large negative value there might be a possible issue. Can I help test?

from systemctl status macfand.service:

Feb 03 16:37:11 Frost macfand[156216]: Fan 1 [CPU & RAM]: 1100 RPM / Target Avg: 50C
Feb 03 16:37:11 Frost macfand[156216]:         TC0P = 53C        TM0P = 48C
Feb 03 16:37:11 Frost macfand[156216]: Fan 2 [Expansion]: -2147483648 RPM / Target Avg: 49C

**Comment by ablakely** [comment]
Hi, have you verified that you're configured for macpro11,5 in the `/etc/macfand.conf` 

Here's the settings for that profile, it seems that my install script didn't set the profile for 11,5 as there's not fans named `CPU & RAM` and `Expansion` in that profile.

https://github.com/ablakely/macfand/blob/master/machines/macbookpro11%2C5.conf
