### ISSUE TITLE
`strlcpy` now in glibc

### ISSUE THREAD

**Issue by whxvd** [ablakely/macfand#8]
When I try to compile `macfand` on Arch Linux, I get the following error:

```
gcc -g3 -std=gnu99 -c -Iinclude -lconfig -lm ./src/config.c   -o ./build/config.o
In file included from ./src/config.c:24:
include/util.h:10:6: error: conflicting types for ‘strlcpy’; have ‘void(char *, const char *, int)’
   10 | void strlcpy(char *to, const char *from, int len);
      |      ^~~~~~~
In file included from ./src/config.c:13:
/usr/include/string.h:506:15: note: previous declaration of ‘strlcpy’ with type ‘size_t(char * restrict,  const char * restrict,  size_t)’ {aka ‘long unsigned int(char * restrict,  const char * restrict,  long unsigned int)’}
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
make: *** [Makefile:24: macfand] Error 1
```

When I remove the declaration and definition of `strlcpy` from `include/util.h` and `src/util.c`, then it builds.

It appears that `strlcpy` has been added to glibc only recently, see https://sourceware.org/pipermail/libc-alpha/2023-July/150524.html.

**Comment by ablakely** [comment]
Thank you for letting me know, I'll work on resolving this weekend.

The mac I was using when I originally wrote this software died and my others are still running macOS so I haven kinda halted development on this but this should be an easy fix.

**Comment by whxvd** [comment]
There is absolutely no urgency from my side. For now, I use `mbpfan` (https://github.com/linux-on-mac/mbpfan). A disadvantage of `mbpfan` is that it currently has no support for GPU temperature sensors. However, the GPU temperature is not critical on my system, so I can live with that.

However, others may run into the issue, as this project is mentioned, e.g., on https://wiki.archlinux.org/title/Mac/Troubleshooting#Fan_Control.

All the best!

**Comment by ablakely** [comment]
The issue should be resolved now.

**Comment by whxvd** [comment]
Thank you for addressing the issue. It compiles now on my Arch Linux system.

However, I think the reason that it compiles is wrong.  You use

```
#ifdef __GLIBC_MINOR__
#if __GLIBC_MINOR >= 38
```

as a test. However, `__GLIBC_MINOR` seems to not be defined, and the preprocessor seems to silently produce a false value in such circumstances. So now the custom `strlcpy` effectively never gets defined. Apart from that, the test would not consider the major version, and it compares the minor version in the wrong direction (`>=` instead of `<`).

I think an appropriate test would be along the following lines:

```
#ifdef __GLIBC__
#if __GLIBC__ < 2 || ( __GLIBC__ == 2 && __GLIBC_MINOR__ < 38)
```

See `/usr/include/features.h` for the definition and documentation of `__GLIBC__` and `__GLIBC_MINOR__`.

**Comment by ablakely** [comment]
> See `/usr/include/features.h` for the definition and documentation of `__GLIBC__` and `__GLIBC_MINOR__`.

Thank you for helping with this I realized that I was doing something wrong since the CI build fails even though builds without error on my local system.  I will fix this
